# Interactive MOEA/D

In [17]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [18]:
import plotly.graph_objects as go
import numpy as np
import pandas as pd
from IPython import display

from desdeo_problem import variable_builder, ScalarObjective, MOProblem
from desdeo_problem.testproblems.TestProblems import test_problem_builder

from desdeo_emo.EAs.NSGAIII import NSGAIII
from desdeo_emo.EAs.RVEA import RVEA
from desdeo_emo.EAs.MOEAD import MOEA_D
from desdeo_emo.EAs.IMOEAD import IMOEA_D
from desdeo_emo.utilities.plotlyanimate import animate_init_, animate_next_
from desdeo_tools.utilities import distance_to_reference_point

## Generate the initial population with MOEA/D

First define the test problem

In [19]:
problem = test_problem_builder(name="DTLZ1", n_of_variables=7, n_of_objectives=3)

In [20]:
evolver = MOEA_D(problem, n_iterations=1, n_gen_per_iter=300)

In [5]:
while evolver.continue_evolution():
    evolver.iterate()

individuals, objective_values = evolver.end()

fig2 = go.Figure(data=go.Scatter3d(x=objective_values[:,0],
                                   y=objective_values[:,1],
                                   z=objective_values[:,2],
                                   mode="markers",
                                   marker_size=1))
print("Ideal point",evolver.population.problem.ideal)
fig2



Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
C

In [6]:
#keep the population to utilize in the interactive version

ini_pop = evolver.population
show_solutions = 10
pref_evolver= IMOEA_D(problem, interact=True, initial_population = ini_pop, n_iterations = 10, n_gen_per_iter = 100, total_function_evaluations=200000)


#ask for preference
pref,plot = pref_evolver.requests()
print(pref[0].content['message'])

Please provide preferences. There is four ways to do this. You can either:

	1: Select preferred solution(s)
	2: Select non-preferred solution(s)
	3: Specify a reference point worse than or equal to the ideal point
	4: Specify desired ranges for objectives.

In case you choose 

1, please specify index/indices of preferred solutions in a numpy array (indexing starts from 0).
For example: 
	numpy.array([1]), for choosing the solutions with index 1.
	numpy.array([2, 4, 5, 16]), for choosing the solutions with indices 2, 4, 5, and 16.

2, please specify index/indices of non-preferred solutions in a numpy array (indexing starts from 0).
For example: 
	numpy.array([3]), for choosing the solutions with index 3.
	numpy.array([1, 2]), for choosing the solutions with indices 1 and 2.

3, please provide a reference point worse than or equal to the ideal point:

f1    0
f2    0
f3    0
Name: ideal, dtype: object
The reference point will be used to focus the reference vectors towards the preferred

### Loop over the following three cells, updating the preferences as desired

Try changing the preference once the Pareto front has been reached.
Note the format of providing the preference.
Check out the content of pref and plot

In [7]:
print(pref[0].content['message'])

Please provide preferences. There is four ways to do this. You can either:

	1: Select preferred solution(s)
	2: Select non-preferred solution(s)
	3: Specify a reference point worse than or equal to the ideal point
	4: Specify desired ranges for objectives.

In case you choose 

1, please specify index/indices of preferred solutions in a numpy array (indexing starts from 0).
For example: 
	numpy.array([1]), for choosing the solutions with index 1.
	numpy.array([2, 4, 5, 16]), for choosing the solutions with indices 2, 4, 5, and 16.

2, please specify index/indices of non-preferred solutions in a numpy array (indexing starts from 0).
For example: 
	numpy.array([3]), for choosing the solutions with index 3.
	numpy.array([1, 2]), for choosing the solutions with indices 1 and 2.

3, please provide a reference point worse than or equal to the ideal point:

f1    0
f2    0
f3    0
Name: ideal, dtype: object
The reference point will be used to focus the reference vectors towards the preferred

In [8]:
response = [0.1,0.1,0.1]
pref_evolver.predefined_distance = 0.4
pref[2].response = pd.DataFrame([response], columns=pref[2].content['dimensions_data'].columns)

In [9]:
pref, plot = pref_evolver.iterate(pref[2])

# show the best solution closest to the reference point
obj = pref_evolver.population.objectives

# achievement function
dist, index = distance_to_reference_point(obj, response[0])

print(f"Distance of best solution to the reference point: {dist}")
print(f"Values of best solution to the reference point: {obj[index]}")

message = (f"Current generation number:{evolver._current_gen_count}. "
           f"Is looping back recommended: {'Yes' if evolver.continue_evolution() else 'No'}")
print(message)
print(pref_evolver.reference_vectors.number_of_vectors)
print(pref_evolver.neighborhoods)

preferencias desde MOEA/D
reference point
[[1.00000000e+00 1.00000000e-05 1.00000000e-05]
 [9.23076923e-01 7.69230769e-02 1.00000000e-05]
 [8.46153846e-01 1.53846154e-01 1.00000000e-05]
 [7.69230769e-01 2.30769231e-01 1.00000000e-05]
 [6.92307692e-01 3.07692308e-01 1.00000000e-05]
 [6.15384615e-01 3.84615385e-01 1.00000000e-05]
 [5.38461538e-01 4.61538462e-01 1.00000000e-05]
 [4.61538462e-01 5.38461538e-01 1.00000000e-05]
 [3.84615385e-01 6.15384615e-01 1.00000000e-05]
 [3.07692308e-01 6.92307692e-01 1.00000000e-05]
 [2.30769231e-01 7.69230769e-01 1.00000000e-05]
 [1.53846154e-01 8.46153846e-01 1.00000000e-05]
 [7.69230769e-02 9.23076923e-01 1.00000000e-05]
 [1.00000000e-05 1.00000000e+00 1.00000000e-05]
 [9.23076923e-01 1.00000000e-05 7.69230769e-02]
 [8.46153846e-01 7.69230769e-02 7.69230769e-02]
 [7.69230769e-01 1.53846154e-01 7.69230769e-02]
 [6.92307692e-01 2.30769231e-01 7.69230769e-02]
 [6.15384615e-01 3.07692308e-01 7.69230769e-02]
 [5.38461538e-01 3.84615385e-01 7.69230769e-02

In [10]:
x = objective_values[:,0]
y = objective_values[:,1]
z = objective_values[:,2]

x2 = obj[:,0]
y2 = obj[:,1]
z2 = obj[:,2]


trace1 = go.Scatter3d(x=x, y=y, z=z, mode="markers",)
trace2 = go.Scatter3d(x=x2, y=y2, z=z2, mode="markers")
trace3 = go.Scatter3d(x=[response[0]], y=[response[1]], z=[response[2]], mode="markers")
fig = go.Figure(data = [trace1, trace2, trace3])
fig.show()

## Giving new preferences

In [11]:
pref, plot = pref_evolver.requests()
print(pref[0].content['message'])

Please provide preferences. There is four ways to do this. You can either:

	1: Select preferred solution(s)
	2: Select non-preferred solution(s)
	3: Specify a reference point worse than or equal to the ideal point
	4: Specify desired ranges for objectives.

In case you choose 

1, please specify index/indices of preferred solutions in a numpy array (indexing starts from 0).
For example: 
	numpy.array([1]), for choosing the solutions with index 1.
	numpy.array([2, 4, 5, 16]), for choosing the solutions with indices 2, 4, 5, and 16.

2, please specify index/indices of non-preferred solutions in a numpy array (indexing starts from 0).
For example: 
	numpy.array([3]), for choosing the solutions with index 3.
	numpy.array([1, 2]), for choosing the solutions with indices 1 and 2.

3, please provide a reference point worse than or equal to the ideal point:

f1    0
f2    0
f3    0
Name: ideal, dtype: object
The reference point will be used to focus the reference vectors towards the preferred

In [12]:

distance = 0.2

preferred_range = np.array([[0.1,0.2],[0.1,0.3],[0.2,0.3]])

pref[3].response = preferred_range

In [13]:
pref, plot = pref_evolver.iterate(pref[3])

# show the best solution closest to the reference point
obj_2 = pref_evolver.population.objectives

# achievement function
dist, index = distance_to_reference_point(obj_2, response[0])

print(f"Distance of best solution to the reference point: {dist}")
print(f"Values of best solution to the reference point: {obj_2[index]}")

message = (f"Current generation number:{pref_evolver._current_gen_count}. "
           f"Is looping back recommended: {'Yes' if pref_evolver.continue_evolution() else 'No'}")
print(message)


preferencias desde MOEA/D
[[0.1 0.2]
 [0.1 0.3]
 [0.2 0.3]]
[False  True False False False False False False False False  True False
  True False False False False  True False False False  True False False
 False False False False False False False False  True  True  True False
 False False False False False False False False False False False False
 False False  True False False False False False False False False  True
 False False False  True False  True False  True False  True False False
 False False  True False False False False False False False False  True
 False False False False False False False False False False  True  True
 False False False False  True  True False False  True]
21
105
84
[[1.00000000e+00 1.00000000e-05 1.00000000e-05]
 [9.16666667e-01 8.33333333e-02 1.00000000e-05]
 [8.33333333e-01 1.66666667e-01 1.00000000e-05]
 [7.50000000e-01 2.50000000e-01 1.00000000e-05]
 [6.66666667e-01 3.33333333e-01 1.00000000e-05]
 [5.83333333e-01 4.16666667e-01 1.00000000e-05]
 [

In [14]:
x = objective_values[:,0]
y = objective_values[:,1]
z = objective_values[:,2]

x2 = obj[:,0]
y2 = obj[:,1]
z2 = obj[:,2]

x3 = obj_2[:,0]
y3 = obj_2[:,1]
z3 = obj_2[:,2]

trace1 = go.Scatter3d(x=x, y=y, z=z, mode="markers",)
trace2 = go.Scatter3d(x=x2, y=y2, z=z2, mode="markers")
trace3 = go.Scatter3d(x=x3, y=y3, z=z3, mode="markers")
trace4 = go.Scatter3d(x=[response[0]], y=[response[1]], z=[response[2]], mode="markers")
fig = go.Figure(data = [trace1, trace2, trace3, trace4])
fig.show()

# Giving preferred solution 